---
title: Team Business
description: We teach the hard-earned lessons of business through face-to-face experiences.
email: info@teambusiness.com # The contact form submission will be done to this email address.
phone: +1-301-537-8980
url: https://teambusiness.com
logo: /assets/images/logo.png # This image will be shown on sharing any page on social media. For example: Homepage, about page etc. This image should be bigger than 200x200px. This image is not used for posts. Posts use their own image mentioned in individual posts.

collections:
  clients:
    title: Clients
    output: false
  team-members:
    title: Team Members
    output: false

# Kramdown is supported by Github
markdown: kramdown

kramdown:
  auto_ids: false

# Jekyll will read contents inside _pages only if we tell it to
include:
  - _pages

# Google Ananlytics Tracker
analytics: UA-92266803-2  # Sign up with Google analytics and replce with your analytics ID

# All compression variables are declared here.
sass:
 sass_dir: /assets/css/_sass
 style: compressed

#compress.html
compress_html:
  clippings: [html, head, meta, title, link, body, div, script, header, footer]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#########################################

exclude:
  - .git

# These plugins are supported by github by default and can be installed locally using ruby gems
plugins:
  - jekyll-sitemap    # Adds sitemap to the website at /sitemap.xml
  - jekyll-feed       # Adds feed to the website at /feed.xml
  - jekyll-seo-tag    # Adds all the important SEO meta tags by default.
  - jekyll-menus      # Adds editable menus in Forestry CMS
