---
title: Team Business
description: We teach the hard-earned lessons of business through face-to-face experiences.
email: info@teambusiness.com # The contact form submission will be done to this email address.
phone: +1-301-537-8980
url: https://teambusiness.com
logo: /assets/images/logo.png # This image will be shown on sharing any page on social media. For example: Homepage, about page etc. This image should be bigger than 200x200px. This image is not used for posts. Posts use their own image mentioned in individual posts.

# Author details shows up at the end of every article
author:
  name: Lara Azzam
  bio: "Lara Bio Here."
  image: author-image.jpg # Choose a 200x200px image and place it inside /images directory.
  facebook: https://facebook.com
  twitter: https://twitter.com

# Kramdown is supported by Github
markdown: kramdown

kramdown:
  auto_ids: false

# Mathjax setting
enable-mathjax: no

# Charts
enable-chartjs: no

# This defines how the URLs should look like
permalink: /blog/:title/

# Pagination - Posts per page in the blog index
paginate: 4
paginate_path: /blog/page:num/

# Define titles for the sections
name: John Doe
projects: I work

# Jekyll will read contents inside _pages only if we tell it to
include:
  - _pages

# Google Ananlytics Tracker
analytics: UA-92266803-2  # Sign up with Google analytics and replce with your analytics ID

# Share buttons
share: no # Change it to `no` to remove share buttons.

# Comments by Disqus # Sign up with Disqus to get your shortcode. Leave it blank if you do not want to run diqus code on the website.
disqus:

# All compression variables are declared here.

sass:
 sass_dir: /assets/css/_sass
 style: compressed

#compress.html
compress_html:
  clippings: [html, head, meta, title, link, body, div, script, header, footer]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#########################################

exclude:
  - .git

# These plugins are supported by github by default and can be installed locally using ruby gems
plugins:
  - jekyll-sitemap    # Adds sitemap to the website at /sitemap.xml
  - jekyll-feed       # Adds feed to the website at /feed.xml
  - jekyll-paginate   # Used for sorting posts by page numbers.
  - jekyll-seo-tag    # Adds all the important SEO meta tags by default.
