---
- title: Educational Institutions
  description: Our simulations give professors, teachers, students, and faculty hands-on,
    active learning experiences that enrich their education. We are not a replacement
    for the lessons learned, we augment the classroom with practical and fundamental
    experience-based examples that help to make the curriculum real.
  fa-icon: fa-graduation-cap
  link: 
- title: Corporations & Non Profits
  description: Our group workshops help your team fully comprehend what complex set
    of decisions go into making a business work. We work alongside your team, guiding
    them through a structured program. Our programs deliver value as BOTH a team-building
    experience and can rapidly improve the business decisions your teams make – leading
    to better collaboration and business results.
  fa-icon: fa-chart-bar
  link: 
- title: Hospitals
  description: Hospitals employ staff that are talented medical professionals – they
    likely lack business acumen knowledge and experience.  With the dramatic changes
    taking place in the hospital industry, business skills are now a critical factor
    for a hospital’s profitability and viability.  Our business workshops fast track
    business acumen learning through hands-on, group-based experiences.  In one day,
    medical staff can learn business concepts and begin to deploy them to their individual
    challenges, as well as those of their hospital. When Team Business workshops are
    deployed across departments and roles, it results in stronger collaboration, driving
    better patient care and financial results.
  fa-icon: fa-hosptial-cross
  link: 
