---
- title: Educational Institutions
  description: Our simulations give professors, teachers, students, and faculty hands-on,
    active learning experiences that enrich their education. We are not a replacement
    for the lessons learned, we augment the classroom with practical and fundamental
    experience-based examples that help to make the curriculum real.
  fa-icon: fa-graduation-cap
  link: 
- title: Corporations & Non Profits
  description: Our group workshops help your team fully comprehend what complex set
    of decisions go into making a business work. We work alongside your team, guiding
    them through a structured program. Our programs can deliver value as a team-building
    experience and can rapidly improve the business decisions your teams make – leading
    to better collaboration and business results.
  fa-icon: fa-chart-bar
  link: 
- title: Corporate Retreats
  description: Our group simulations and narrative-based exercises help your team
    fully comprehend what complex set of decisions go into making a business work.
    We work alongside your team, guiding them through a structured program. Better
    than a trust fall.
  fa-icon: fa-chart-bar
  link: 
